version: "1.0.0.{build}"
image: Visual Studio 2017

environment:
  SOLUTION: PickYourTunes
  PROJECT: PickYourTunes

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

before_build:
  - cmd: nuget restore %SOLUTION%.sln

build_script:
  - cmd: msbuild.exe %SOLUTION%.sln /t:Build /p:Configuration=Release;Platform=x64

after_build:
  - cmd: 7z a %SOLUTION%.7z %APPVEYOR_BUILD_FOLDER%\%PROJECT%\bin\x64\Release\*

artifacts:
  - path: "%SOLUTION%.7z"
    name: Mod Build

deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: "DkvKC8KRj8AipGu/oWW/J2e6jMWt2xXQfKU7oefFMsp0ZMfzz+OR9Y9XpML+ZmG4"
  artifact: "%SOLUTION%.7z"
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
